apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- #haproxy#
controlPlaneEndpoint: "#haproxy#:6443"
etcd:
  external:
    endpoints:
    - https://#master1#:2379
    - https://#master2#:2379
    - https://#master3#:2379
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 10.30.0.0/24
apiServerExtraArgs:
  apiserver-count: "3"