- hosts: localhost
  gather_facts: no
  tasks: 
    - name: Init Scripts
      shell: |
        chmod +x /ansible/create_servers.sh
        chmod +x /ansible/init.sh
        /ansible/create_servers.sh
        /ansible/init.sh
    - name: Create Certificates
      become: true
      shell: |
        cd /ansible/create_certs/
        chmod +x /ansible/create_certs/create_certs.sh
        /ansible/create_certs/create_certs.sh        
- hosts: all
  gather_facts: no
  tasks:
    - name: Need Restart Set Auto
      shell: sed -i "s/#\$nrconf{restart} \= 'i';/\$nrconf{restart} \= 'a';/g" /etc/needrestart/needrestart.conf
    - name: Install Bash Completion
      shell: |
              apt install bash-completion
              source /usr/share/bash-completion/bash_completion
              kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
              echo 'alias k=kubectl' >>~/.bashrc
              echo 'complete -o default -F __start_kubectl k' >>~/.bashrc
    - name: Install HAproxy Server
      become: true 
      shell: |
        wget https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin
        apt update -y 
        apt upgrade -y
        apt install haproxy -y
        systemctl enable haproxy
      when: inventory_hostname in groups['haproxy']
    - name: Copy Config HAproxy Server
      become: true 
      copy:
        src: /ansible/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      when: inventory_hostname in groups['haproxy']
    - name: Start HAproxy Server
      become: true 
      shell: |
        echo "#" >> /etc/haproxy/haproxy.cfg
        systemctl stop haproxy
        systemctl start haproxy
      when: inventory_hostname in groups['haproxy']
    - name: Copy Certificates to Masters
      copy:
        src: /ansible/create_certs/
        dest: /root/certs/
      when: inventory_hostname in groups['master']
    - name: Install ETCD to Masters Server
      become: true 
      shell: |
        rm -rf /etc/etcd
        mkdir /etc/etcd /var/lib/etcd
        mv /root/certs/ca.pem /root/certs/kubernetes.pem /root/certs/kubernetes-key.pem /etc/etcd
        wget https://github.com/etcd-io/etcd/releases/download/v3.5.5/etcd-v3.5.5-linux-amd64.tar.gz
        tar xvzf etcd-v3.5.5-linux-amd64.tar.gz
        mv etcd-v3.5.5-linux-amd64/etcd* /usr/local/bin/
      when: inventory_hostname in groups['master']
    - name: Copy Service File to Master1 Server
      copy:
        src: /ansible/etcd_master1.service
        dest: /etc/systemd/system/etcd.service
      when: inventory_hostname in groups['master1']
    - name: Copy Service File to Master2 Server
      copy:
        src: /ansible/etcd_master2.service
        dest: /etc/systemd/system/etcd.service
      when: inventory_hostname in groups['master2']
    - name: Copy Service File to Master3 Server
      copy:
        src: /ansible/etcd_master3.service
        dest: /etc/systemd/system/etcd.service
      when: inventory_hostname in groups['master3']
    - name: Start ETCD all Masters
      shell: |
        systemctl daemon-reload
        systemctl enable etcd
        systemctl restart etcd
        ETCDCTL_API=3 etcdctl member list
      when: inventory_hostname in groups['master']
    - name: Copy Init Kubernetes Config
      become: true 
      copy:
        src: /ansible/config.yaml
        dest: /root/config.yaml
      when: inventory_hostname in groups['master']
    - name: Disable swap and add kernel settings
      shell: |
              swapoff -a
              sed -e '/swap/ s/^#*/#/' -i /etc/fstab
              systemctl mask swap.target
              tee /etc/modules-load.d/containerd.conf <<EOF
              overlay
              br_netfilter
              EOF
              modprobe overlay
              modprobe br_netfilter
              tee /etc/sysctl.d/kubernetes.conf <<EOF
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
              EOF
              sysctl --system
      when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker'] 
    - name: Install containerd runtime
      shell: |
              apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              apt update
              apt install -y containerd.io
              containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
              sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
              systemctl restart containerd
              systemctl enable containerd
      when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker']              
    - name: Crictl Install
      shell: |
              VERSION="v1.24.1"
              curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz
              tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
              rm -f crictl-$VERSION-linux-amd64.tar.gz
              crictl config runtime-endpoint unix:///run/containerd/containerd.sock                                                          
              crictl config image-endpoint unix:///run/containerd/containerd.sock
      when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker']             
    - name: Add apt repository for Kubernetes
      shell: |
              curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
              apt-add-repository -y "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker']    
    - name: Install Kubernetes components Kubectl kubeadm and kubelet
      shell: |
              apt update
              apt install -y kubelet kubeadm kubectl
              systemctl enable kubelet
      when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker']
    - name: Init First Kubernetes Master
      become: true
      shell: kubeadm init --config=/root/config.yaml 
      when: inventory_hostname in groups['master1']
- hosts: master1
  gather_facts: no
  tasks:
    - name: Find Certificates to copy
      find:
        paths: "/etc/kubernetes/pki/"
        recurse: yes
      register: files_to_copy
      when: inventory_hostname in groups['master1']
    - name: Get Kubernetes Certificates
      fetch:
        src: "{{ item.path }}"
        dest: /ansible/pki/
        flat: yes
      with_items: "{{ files_to_copy.files }}"
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Deleting Apiserver Certificates
      shell: rm -rf /ansible/pki/apiserver.*
- hosts: all
  gather_facts: no
  tasks:
    - name: Copy Certificates to other Masters
      become: true 
      copy:
        src: /ansible/pki
        dest: /etc/kubernetes/
      when: inventory_hostname in groups['master2'] or inventory_hostname in groups['master3']
    - name: Kubernetes Init Other Masters
      shell: kubeadm init --config=config.yaml
      when: inventory_hostname in groups['master2'] or inventory_hostname in groups['master3']
    - name: Add Permision Admin Conf
      shell: chmod +r /etc/kubernetes/admin.conf
      when: inventory_hostname in groups['master1']
    - name: Get Admin Conf
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /ansible/admin.conf
        flat: yes
      when: inventory_hostname in groups['master1']
    - name: Copy Admin Conf File to HAproxy Server
      copy:
        src: /ansible/admin.conf
        dest: /root/admin.conf
      when: inventory_hostname in groups['haproxy']
    - name: HAproxy Settings
      shell: |
        mkdir /root/.kube
        mv /root/admin.conf /root/.kube/config
        chmod 600 /root/.kube/config
      when: inventory_hostname in groups['haproxy']
    - name: Remove Permision Admin Conf
      shell: chmod 600 /etc/kubernetes/admin.conf
      when: inventory_hostname in groups['master1']
    - name: Helm Install
      shell: |
              curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
              chmod 700 get_helm.sh
              ./get_helm.sh
      when: inventory_hostname in groups['master']               
    - name: Calico Install
      shell: |
              curl https://projectcalico.docs.tigera.io/manifests/calico.yaml -O
              kubectl apply -f calico.yaml      
      
      
      