- hosts: all
  gather_facts: no
  tasks:
    - name: Need Restart Set Auto
      shell: sed -i "s/#\$nrconf{restart} \= 'i';/\$nrconf{restart} \= 'a';/g" /etc/needrestart/needrestart.conf
    - name: Install Bash Completion
      shell: |
              apt-get install bash-completion
              source /usr/share/bash-completion/bash_completion
              kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
              echo 'alias k=kubectl' >>~/.bashrc
              echo 'complete -o default -F __start_kubectl k' >>~/.bashrc      
    - name: Init Scripts
      shell: |
        chmod +x /ansible/init.sh
        /ansible/init.sh             
      delegate_to: localhost
    - name: Create Certificates
      become: true
      shell: |
        cd /ansible/create_certs/
        chmod +x /ansible/create_certs/create_certs.sh
        /ansible/create_certs/create_certs.sh           
      delegate_to: localhost
    - name: Install HAproxy Server
      become: true 
      shell: |
        wget https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin
        apt update -y 
        apt upgrade -y
        apt install haproxy -y
        systemctl enable haproxy
      when: inventory_hostname in groups['HAproxy']
    - name: Copy Config HAproxy Server
      become: true 
      copy:
        src: /ansible/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      when: inventory_hostname in groups['HAproxy']
    - name: Start HAproxy Server
      become: true 
      shell: systemctl restart haproxy
      when: inventory_hostname in groups['HAproxy']      
    - name: Copy Certificates to Masters
      copy:
        src: /ansible/create_certs/
        dest: /root/certs/
      when: inventory_hostname in groups['master']    
    - name: Install ETCD to Masters Server
      become: true 
      shell: |
        mkdir /etc/etcd /var/lib/etcd
        mv /root/ca.pem /root/kubernetes.pem /root/kubernetes-key.pem /etc/etcd
        wget https://github.com/etcd-io/etcd/releases/download/v3.5.5/etcd-v3.5.5-linux-amd64.tar.gz
        tar xvzf etcd-v3.5.5-linux-amd64.tar.gz
        mv etcd-v3.5.5-linux-amd64/etcd* /usr/local/bin/
      when: inventory_hostname in groups['master']
    - name: Copy Install script to Masters Server
      copy:
        src: /ansible/etcd_master1.service
        dest: /etc/systemd/system/etcd.service
      when: inventory_hostname in groups['master1']
    - name: Copy Install script to Masters Server
      copy:
        src: /ansible/etcd_master2.service
        dest: /etc/systemd/system/etcd.service
      when: inventory_hostname in groups['master2']
    - name: Copy Install script to Masters Server
      copy:
        src: /ansible/etcd_master3.service
        dest: /etc/systemd/system/etcd.service
      when: inventory_hostname in groups['master3']
    - name: Start ETCD all Masters
      shell: |
        systemctl daemon-reload
        systemctl enable etcd
        systemctl start etcd
        ETCDCTL_API=3 etcdctl member list
      when: inventory_hostname in groups['master']
    - name: Copy Init Kubernetes Config
      become: true 
      copy:
        src: /ansible/config.yaml
        dest: /root/config.yaml
      when: inventory_hostname in groups['master']     